baseURL: "https://a-bhagava.github.io" 
title: Anvita Bhagavathula
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Teaching/Leadership
          url: location/
          weight: 3
        - name: CV
          url: /CV.pdf
          weight: 4

params:
    description: 
    author: Anvita Bhagavathula
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Anvita Bhagavathula
          subtitle: | 
            Hi, I’m Anvi! I’m a second-year EECS PhD student at MIT, where I’m advised by Priya Donti.
            My research focuses on alleviating the limitations/bottlenecks of traditional scientific computing methods (e.g., differential equation simulations, iterative solvers) using physics-informed machine learning. My work specifically seeks to address challenges in renewable energy, climate, and power systems applications.
          research: |
            My current projects include (1) 
            developing physics-informed machine learning models for solving partial differential equations (PDEs), with applications to accelerating computational fluid dynamics simulations of wind farms (2) designing ML-based power flow solvers using graph learning techniques. Beyond these projects, I am also interested in exploring problems related to weather forecasting and carbon capture.
            Key themes that I explore through my research include: 
            1. Incorporating physics and domain structure into ML models through soft and hard constraints, operator learning, and graph-based methods.
            2. Taking inspiration from numerical solvers (e.g., spectral and wavelet methods) to inform the design of these models.
            3. Developing models that are accessible even in compute-constrained and low-data regimes (e.g., via self-supervised training and multi-fidelity approaches).

          aboutme: |
            I completed my undergraduate degree at Brown University, where I majored in Physics and Applied Mathematics, followed by a Master’s in Electrical and Computer Engineering at Cornell Tech. As an undergrad/master's student, I engaged in a broad range of research experiences involving scientific computing.
            At Brown, I studied superconductivity in 2D graphene systems using experimental methods and Density Functional Theory (DFT) simulations in the
            <a href="https://sites.brown.edu/li-lab/" target="_blank" rel="noopener" style="color: #3399ff;">Low-Dimensional Electronics Lab</a>
            (advisors: Jia Li, Brenda Rubenstein). In addition, I developed physics-informed neural networks as part of the
            <a href="https://sites.brown.edu/crunch-group/" target="_blank" rel="noopener" style="color: #3399ff;">The Crunch Group</a>
            (advisor: Somdatta Goswami).
            I also had the opportunity to intern at 
            <a href="https://www.microsoft.com/en-us/research/group/research-for-industry/" target="_blank" rel="noopener" style="color: #3399ff;">Microsoft Research</a>
            (advisor: Ranveer Chandra) where I worked on creating datasets for food protein property prediction, and 
            startups such as <a href="https://www.aqemia.com/" target="_blank" rel="noopener" style="color: #3399ff;">Aqemia</a> (drug discovery) and
            <a href="https://transcelestial.com/" target="_blank" rel="noopener" style="color: #3399ff;">Transcelestial</a> (wireless laser communications).

            Outside of work, I love singing, playing piano, composing music, and reading poetry. 
            I’ve recently started exploring cooking and creating new recipes. 
            I also enjoy film photography, and you can find some of my photos 
            <a href="https://www.instagram.com/anvi_film/" target="_blank" rel="noopener" style="color: #3399ff;">here</a>!
          imageUrl: "profile_pic.png"
          imageWidth: 190
          imageHeight: 190
          buttons:
            - name: Publications
              url: publications/
            - name: Projects
              url: projects/
            - name: Teaching/Leadership
              url: location/
            - name: CV
              url: cv.pdf
          updates:
            - date: "Sep 18, 2025"
              text: ' A revised version of <i><a href="https://arxiv.org/abs/2510.22048">PF∆: A Benchmark Dataset for Power Flow with Load, Generator, & Topology Variations</a></i> was accepted to <i>NeurIPS 2025 (Datasets & Benchmarks Track)</i>.'

            - date: "Apr 25, 2025"
              text: '<i><a href="https://www.climatechange.ai/papers/iclr2025/67">PF∆: A Benchmark Dataset for Power Flow with Load, Generator, & Topology Variations</a></i> was accepted to the <i>Tackling Climate Change with AI</i> workshop at <i>ICLR 2025</i>.'

            - date: "Sep 3, 2024"
              text: "Started my PhD in the EECS department at MIT where I will be advised by Professor Priya Donti."

            - date: "Jul 9, 2024"
              text: 'Presented my paper <i><a href="https://hotcarbon.org/assets/2024/pdf/hotcarbon24-final146.pdf">Understanding the Implications of Uncertainty in Embodied Carbon Models for Sustainable Computing</a></i> at <i>HotCarbon’24</i>.'


    socialIcons:
        - name: Email
          url: abhagava@mit.edu
        - name: linkedin
          url: https://www.linkedin.com/in/anvita-bhagavathula/
        - name: google scholar
          url: https://scholar.google.com/citations?user=3zq31nwAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/a-bhagava
        - name: Twitter
          url: https://x.com/anvita_b_

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Anvita Bhagavathula"
      icon: favicon-2025.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2